/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ammSol from "./amm.sol";
export type { ammSol };
import type * as erc20DemoSol from "./erc20.demo.sol";
export type { erc20DemoSol };
